### ISSUE TITLE
Lexicon/Strongs word count accuracy

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord-box3/book-package#13]

**Comment by mandolyte** [comment]
Article G01520 has a number of odd things. I guess since this is hand-written, I can't expect a whole lot. Found: abbreviations, invalid markdown links, inconsistent bookIds, etc. Below is the "citations" section. My word count for this text fragment is 18. The 18 words my counter finds follow the text.

```
shame (MM, VGT, s.v.): subjectively, [Lk 14:19](Luk 14:19), [II Co 4:2](2Co 4:2); objectively, [Phl 3:19](Php 3:19), [He 12:2](Heb 12:2); as something to be ashamed of, [Re 3:18](Rev 3:18); pl. (Bl., §32, 6), shameful deeds, [Ju 13](Jud 1:13).†
```

Here are the 18 words in the above:
```
shame
mm
vgt
sv
subjectively
objectively
as
something
to
be
ashamed
of
pl
bl
32
6
shameful
deeds
```

**Comment by jag3773** [comment]
The lexicons are undergoing heavy revision and what you posted is what I would expect at this point.  Don't worry about doing anything special for the lexicon entries currently.
