### ISSUE TITLE
Material Table enhancement

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord-box3/book-package#31]
Switch to NPM Material Table component.

Question: do we need the word order table that shows all words in the lexical order found? If not just show the word frequency table.

Another option is to put both tables into their own collapsible section.

**Comment by jag3773** [comment]
I think we just want the word frequency table.

**Comment by mandolyte** [comment]
@jag3773 I replaced existing word frequency tables with the new material table component. I also added one to the package totals.

Other "details" have tables that list contributing articles; I left them the way they are for now.

Let me know if you see any other visual UI changes needed.

**Comment by mandolyte** [comment]
Ok, this is done. Here is the rule of thumb:
- where the data is book oriented (UTN, UTQ, ULT, UST), I used the word frequency table.
- otherwise (UTW, UTA), I used a table that showed data for each referenced article
- altho Strongs isn't part of the rollup, the component is still available and it displays like UTW and UTA

@jag3773
